version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  postgres_notification:
    image: postgres:14
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"

  postgres_task:
    image: postgres:14
    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"

  postgres_user:
    image: postgres:14
    environment:
      POSTGRES_DB: user_manager_db
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5435:5432"

  notification_manager:
    build:
      context: ./notification_manager
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - kafka
      - postgres_notification

  task_manager:
    build:
      context: ./task_manager
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - kafka
      - postgres_task

  user_manager:
    build:
      context: ./user_manager
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      - kafka
